### PR TITLE
Removing transitive dependencies K4Kotlin and Android Databinding

### PR DESCRIPTION
**Pull request by SebastianEngel**
When the QuickPermissions-Kotlin library is integrated into app projects, it unfortunately brings transitive dependencies with it, which the using application may not want.

The usage of [K4Kotlin](https://github.com/kirtan403/K4Kotlin) automatically introduces another transitive dependency on Android Databinding. Both of these libraries are then forced onto the using app, which also [requires adding proguard rules for databinding](https://github.com/QuickPermissions/QuickPermissions/issues/1).

The internal usage of K4Kotlin is very low. All of the usages can easily be replaced with default functionality from the support lib. This pull request does exactly that and so removes both of these dependencies.

### CODE REVIEW

**Comment by kirtan403** [comment]
@SebastianEngel  Thank you so much for the pull request. K4kotlin is pretty lightweight. I will review the changes and its impact. Please allow me some time

**Comment by SebastianEngel** [comment]
Hi @kirtan403, did you find some time to have a look into it?

**Comment by carterhudson** [comment]
I'm going to have to stop using your library. You depend on a deprecated Kotlin versoin, not to mention the issues above.

**Comment by carterhudson** [comment]
Decided to use @SebastianEngel 's commit instead. Please maintain your library.

**Comment by kirtan403** [comment]
@SebastianEngel  I have merged the changes. Will release the new version soon. Sorry for the delay..

**Comment by kirtan403** [comment]
@carterhudson  I couldn't get the much time. Sorry about that, I am updating versions now.

**Comment by kirtan403** [comment]
Release a new version: https://github.com/QuickPermissions/QuickPermissions-Kotlin/releases/tag/0.3.0

**Pull request merged**
